#!/usr/bin/env python3
"""m720-config — local web UI for configuring Logitech M720 buttons via logiops.

Started by `mouse modify`. Binds 127.0.0.1 only, requires a per-run token, and
never writes to /etc itself — all privileged work goes through mouse-apply.
"""

from __future__ import annotations

import json
import os
import re
import secrets
import shutil
import subprocess
import sys
import tempfile
import threading
import time
import webbrowser
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path

LIB_DIR = Path(__file__).resolve().parent
UI_FILE = LIB_DIR / "ui.html"
LOGID_CFG = Path("/etc/logid.cfg")
APPLY_HELPER = "/usr/local/bin/mouse-apply"
SERVICE = "mouse.service"
CONFIG_HOME = Path(os.environ.get("XDG_CONFIG_HOME", Path.home() / ".config")) / "m720-config"
PROFILES_FILE = CONFIG_HOME / "profiles.json"

DEFAULT_DEVICE = "M720 Triathlon Multi-Device Mouse"

# The six remappable HID++ control IDs on the M720, in the order the UI shows
# them. Confirmed against the device's own asset manifest.
BUTTONS = [
    {"cid": "0x52", "name": "Wheel click", "hint": "Middle button"},
    {"cid": "0x53", "name": "Back", "hint": "Thumb-side rear"},
    {"cid": "0x56", "name": "Forward", "hint": "Thumb-side front"},
    {"cid": "0x5b", "name": "Wheel tilt left", "hint": "Push wheel left"},
    {"cid": "0x5d", "name": "Wheel tilt right", "hint": "Push wheel right"},
    {"cid": "0xd0", "name": "Gesture button", "hint": "Large thumb rest button"},
]
VALID_CIDS = {b["cid"] for b in BUTTONS}


# --------------------------------------------------------------------------
# logid.cfg generation
# --------------------------------------------------------------------------

def _keys_literal(keys):
    safe = [k for k in keys if re.fullmatch(r"(KEY|BTN)_[A-Z0-9_]+", str(k))]
    return "[" + ", ".join(f'"{k}"' for k in safe) + "]"


def _emit_action(action, indent):
    """Render one action block body (the part inside `action = { ... }`)."""
    pad = " " * indent
    kind = (action or {}).get("type", "none")

    if kind == "keypress":
        keys = action.get("keys") or []
        if not keys:
            return f'{pad}type: "None";\n'
        return f'{pad}type: "Keypress";\n{pad}keys: {_keys_literal(keys)};\n'

    if kind == "changehost":
        host = action.get("host", "next")
        if host in ("next", "prev"):
            return f'{pad}type: "ChangeHost";\n{pad}host: "{host}";\n'
        try:
            n = int(host)
        except (TypeError, ValueError):
            n = 1
        return f'{pad}type: "ChangeHost";\n{pad}host: {max(1, min(3, n))};\n'

    if kind == "cycledpi":
        dpis = [int(d) for d in (action.get("dpis") or [1000]) if str(d).isdigit()]
        dpis = dpis or [1000]
        return f'{pad}type: "CycleDPI";\n{pad}dpis: [{", ".join(str(d) for d in dpis)}];\n'

    if kind == "changedpi":
        inc = int(action.get("inc", 100))
        return f'{pad}type: "ChangeDPI";\n{pad}inc: {inc};\n'

    if kind == "togglesmartshift":
        return f'{pad}type: "ToggleSmartShift";\n'

    if kind == "togglehiresscroll":
        return f'{pad}type: "ToggleHiresScroll";\n'

    if kind == "gestures":
        out = [f'{pad}type: "Gestures";\n', f"{pad}gestures: (\n"]
        entries = []
        for direction in ("Up", "Down", "Left", "Right", "None"):
            sub = (action.get("gestures") or {}).get(direction.lower())
            # "default" means the direction is unassigned -> omit it entirely.
            # "none" is an explicit "do nothing" -> emit a None action.
            if not sub or sub.get("type", "default") == "default":
                continue
            gpad = " " * (indent + 4)
            body = [f"{gpad}{{\n"]
            body.append(f'{gpad}    direction: "{direction}";\n')
            body.append(f'{gpad}    mode: "OnRelease";\n')
            threshold = sub.get("threshold")
            if direction != "None" and threshold:
                body.append(f"{gpad}    threshold: {int(threshold)};\n")
            body.append(f"{gpad}    action =\n{gpad}    {{\n")
            body.append(_emit_action(sub, indent + 12))
            body.append(f"{gpad}    }};\n")
            body.append(f"{gpad}}}")
            entries.append("".join(body))
        out.append(",\n".join(entries) + "\n")
        out.append(f"{pad});\n")
        return "".join(out)

    return f'{pad}type: "None";\n'


def generate_config(model):
    """Turn the UI's JSON model into a logid.cfg document."""
    device = model.get("device") or DEFAULT_DEVICE
    device = re.sub(r'[^\w \-\.]', "", str(device))[:80]
    settings = model.get("settings") or {}
    buttons = model.get("buttons") or {}

    lines = [
        "// Generated by m720-config (`mouse modify`).\n",
        "// Hand edits are safe but will be replaced the next time you hit Apply.\n",
        f"// {time.strftime('%Y-%m-%d %H:%M:%S %Z')}\n",
        "\n",
        "devices: (\n",
        "{\n",
        f'    name: "{device}";\n',
    ]

    if settings.get("dpi"):
        lines.append(f"    dpi: {int(settings['dpi'])};\n")
    if settings.get("smartshift_enabled"):
        lines.append("    smartshift:\n    {\n")
        lines.append(f"        on: {'true' if settings.get('smartshift_on') else 'false'};\n")
        lines.append(f"        threshold: {int(settings.get('smartshift_threshold', 30))};\n")
        lines.append("    };\n")
    if settings.get("hiresscroll_enabled"):
        lines.append("    hiresscroll:\n    {\n")
        lines.append(f"        hires: {'true' if settings.get('hiresscroll_hires') else 'false'};\n")
        lines.append(f"        invert: {'true' if settings.get('hiresscroll_invert') else 'false'};\n")
        lines.append(f"        target: {'true' if settings.get('hiresscroll_target') else 'false'};\n")
        lines.append("    };\n")

    blocks = []
    for spec in BUTTONS:
        cid = spec["cid"]
        entry = buttons.get(cid)
        if not entry:
            continue
        kind = entry.get("type", "default")
        if kind == "default":
            # Leave the button untouched so the hardware default survives.
            continue
        label = entry.get("label")
        label = re.sub(r"[\r\n]", " ", str(label))[:60] if label else ""
        heading = f"{spec['name']} -> {label}" if label else spec["name"]
        block = [f"        // {heading}\n"]
        block.append("        {\n")
        block.append(f"            cid: {cid};\n")
        block.append("            action =\n            {\n")
        block.append(_emit_action(entry, 16))
        block.append("            };\n")
        block.append("        }")
        blocks.append("".join(block))

    if blocks:
        lines.append("\n    buttons: (\n")
        lines.append(",\n\n".join(blocks) + "\n")
        lines.append("    );\n")

    lines.append("}\n);\n")
    return "".join(lines)


# --------------------------------------------------------------------------
# logid.cfg parsing (tolerant — best effort, never fatal)
# --------------------------------------------------------------------------

def _split_blocks(text):
    """Split a libconfig list body into top-level {...} chunks."""
    out, depth, start, in_str = [], 0, None, False
    i = 0
    while i < len(text):
        ch = text[i]
        if in_str:
            if ch == "\\":
                i += 2
                continue
            if ch == '"':
                in_str = False
        elif ch == '"':
            in_str = True
        elif ch == "{":
            if depth == 0:
                start = i
            depth += 1
        elif ch == "}":
            depth -= 1
            if depth == 0 and start is not None:
                out.append(text[start + 1:i])
                start = None
        i += 1
    return out


def _named_list(text, key):
    """Return the body of `key: ( ... )` at any depth, or ''."""
    m = re.search(rf"\b{key}\s*[:=]\s*\(", text)
    if not m:
        return ""
    depth, i = 0, m.end() - 1
    while i < len(text):
        if text[i] == "(":
            depth += 1
        elif text[i] == ")":
            depth -= 1
            if depth == 0:
                return text[m.end():i]
        i += 1
    return ""


def _parse_action(block):
    kind = re.search(r'type\s*[:=]\s*"(\w+)"', block)
    kind = (kind.group(1) if kind else "None").lower()

    if kind == "keypress":
        keys = re.search(r"keys\s*[:=]\s*\[([^\]]*)\]", block)
        found = re.findall(r'"((?:KEY|BTN)_[A-Z0-9_]+)"', keys.group(1) if keys else "")
        return {"type": "keypress", "keys": found}

    if kind == "changehost":
        host = re.search(r'host\s*[:=]\s*(?:"(\w+)"|(\d+))', block)
        val = (host.group(1) or host.group(2)) if host else "next"
        return {"type": "changehost", "host": val}

    if kind == "cycledpi":
        dpis = re.search(r"dpis\s*[:=]\s*\[([^\]]*)\]", block)
        nums = [int(n) for n in re.findall(r"\d+", dpis.group(1) if dpis else "")]
        return {"type": "cycledpi", "dpis": nums or [1000]}

    if kind == "changedpi":
        inc = re.search(r"inc\s*[:=]\s*(-?\d+)", block)
        return {"type": "changedpi", "inc": int(inc.group(1)) if inc else 100}

    if kind == "togglesmartshift":
        return {"type": "togglesmartshift"}
    if kind == "togglehiresscroll":
        return {"type": "togglehiresscroll"}

    if kind == "gestures":
        gestures = {}
        for g in _split_blocks(_named_list(block, "gestures")):
            direction = re.search(r'direction\s*[:=]\s*"(\w+)"', g)
            if not direction:
                continue
            inner = re.search(r"action\s*[:=]\s*\{", g)
            sub = _parse_action(g[inner.end():] if inner else g)
            threshold = re.search(r"threshold\s*[:=]\s*(\d+)", g)
            if threshold:
                sub["threshold"] = int(threshold.group(1))
            gestures[direction.group(1).lower()] = sub
        return {"type": "gestures", "gestures": gestures}

    return {"type": "none"}


def parse_config(text):
    """Best-effort read of an existing logid.cfg into the UI model."""
    model = {"device": DEFAULT_DEVICE, "settings": {}, "buttons": {}}
    if not text:
        return model

    name = re.search(r'name\s*[:=]\s*"([^"]+)"', text)
    if name:
        model["device"] = name.group(1)

    dpi = re.search(r"^\s*dpi\s*[:=]\s*(\d+)", text, re.M)
    if dpi:
        model["settings"]["dpi"] = int(dpi.group(1))

    for block in _split_blocks(_named_list(text, "buttons")):
        cid = re.search(r"cid\s*[:=]\s*(0[xX][0-9a-fA-F]+|\d+)", block)
        if not cid:
            continue
        raw = cid.group(1)
        norm = f"0x{int(raw, 16 if raw.lower().startswith('0x') else 10):02x}"
        if norm not in VALID_CIDS:
            continue
        inner = re.search(r"action\s*[:=]\s*\{", block)
        model["buttons"][norm] = _parse_action(block[inner.end():] if inner else block)

    return model


def read_current_config():
    """Read /etc/logid.cfg, falling back to sudo -n if it is not world-readable."""
    try:
        return LOGID_CFG.read_text(), None
    except FileNotFoundError:
        return None, "no /etc/logid.cfg yet"
    except PermissionError:
        try:
            r = subprocess.run(["sudo", "-n", "cat", str(LOGID_CFG)],
                               capture_output=True, text=True, timeout=5)
            if r.returncode == 0:
                return r.stdout, None
        except Exception:
            pass
        return None, "/etc/logid.cfg is not readable by your user"
    except OSError as exc:
        return None, str(exc)


# --------------------------------------------------------------------------
# Scroll speed (imwheel)
#
# logiops has no scroll-speed setting: its device-level knobs are dpi,
# smartshift, hiresscroll and thumbwheel, none of which change how far a
# ratcheted wheel scrolls. On X11 the tool for that is imwheel, which
# intercepts wheel buttons 4/5 and re-emits them N times. It runs as your
# user, so nothing here needs root.
# --------------------------------------------------------------------------

IMWHEELRC = Path.home() / ".imwheelrc"
AUTOSTART = (Path(os.environ.get("XDG_CONFIG_HOME", Path.home() / ".config"))
             / "autostart" / "m720-imwheel.desktop")
IMWHEEL_CMD = ['imwheel', '-k', '-b', '4 5']
IMWHEEL_EXEC = 'imwheel -k -b "4 5"'   # quoted form for the .desktop file


def imwheel_state():
    """What imwheel is doing right now, and what our rc file asks for."""
    installed = shutil.which("imwheel") is not None
    running = False
    if installed:
        try:
            running = subprocess.run(["pgrep", "-x", "imwheel"],
                                     capture_output=True, timeout=5).returncode == 0
        except Exception:
            pass

    lines, invert = 3, False
    try:
        rc = IMWHEELRC.read_text()
        m = re.search(r"^None,\s*Up,\s*Button(\d),\s*(\d+)", rc, re.M)
        if m:
            invert = m.group(1) == "5"
            lines = int(m.group(2))
    except OSError:
        pass

    return {
        "installed": installed,
        "running": running,
        "enabled": running and IMWHEELRC.exists(),
        "lines": lines,
        "invert": invert,
    }


def write_imwheelrc(lines, invert):
    up, down = ("Button5", "Button4") if invert else ("Button4", "Button5")
    n = max(1, min(20, int(lines)))
    out = [
        "# Generated by m720-config (`mouse modify`).\n",
        "# The trailing number is how many scroll steps one wheel click sends.\n",
        '".*"\n',
        f"None,      Up,   {up}, {n}\n",
        f"None,      Down, {down}, {n}\n",
    ]
    # Pass modified scrolling through untouched, so Ctrl+wheel zoom and
    # Shift+wheel horizontal scroll still move one step at a time.
    for mod in ("Control_L", "Shift_L", "Alt_L"):
        out.append(f"{mod}, Up,   {mod}|{up}\n")
        out.append(f"{mod}, Down, {mod}|{down}\n")
    IMWHEELRC.write_text("".join(out))


def write_autostart(enable):
    try:
        if not enable:
            AUTOSTART.unlink(missing_ok=True)
            return
        AUTOSTART.parent.mkdir(parents=True, exist_ok=True)
        AUTOSTART.write_text(
            "[Desktop Entry]\nType=Application\nName=M720 scroll speed\n"
            "Comment=imwheel, configured by m720-config\n"
            # Desktop-entry Exec splits on whitespace, so the button list
            # must stay quoted or imwheel sees a stray "5" argument.
            f'Exec={IMWHEEL_EXEC}\n'
            "X-GNOME-Autostart-enabled=true\nNoDisplay=true\n")
    except OSError:
        pass


def apply_scroll(settings):
    """Apply scroll settings. Returns (ok, message). Never raises."""
    cfg = (settings or {}).get("scroll") or {}
    if not cfg.get("enabled"):
        try:
            subprocess.run(["pkill", "-x", "imwheel"], capture_output=True, timeout=5)
        except Exception:
            pass
        write_autostart(False)
        return True, "scroll speed left at the system default"

    if not shutil.which("imwheel"):
        return False, ("scroll speed needs imwheel, which is not installed. "
                       "Install it with:  sudo apt install imwheel")

    try:
        write_imwheelrc(cfg.get("lines", 3), cfg.get("invert", False))
    except OSError as exc:
        return False, f"could not write {IMWHEELRC}: {exc}"

    try:
        # -k replaces any running instance; -b limits us to the vertical wheel
        # so remapped tilt buttons (6/7) are left alone.
        r = subprocess.run(IMWHEEL_CMD, capture_output=True, text=True, timeout=10)
    except Exception as exc:
        return False, f"could not start imwheel: {exc}"
    if r.returncode != 0:
        return False, (r.stderr or r.stdout or "imwheel failed to start").strip()

    write_autostart(True)
    n = max(1, min(20, int(cfg.get("lines", 3))))
    return True, f"scroll speed set to {n} step{'s' if n != 1 else ''} per click"


# --------------------------------------------------------------------------
# Service interaction
# --------------------------------------------------------------------------

def service_status():
    def sh(args):
        try:
            return subprocess.run(args, capture_output=True, text=True,
                                  timeout=5).stdout.strip()
        except Exception:
            return ""

    active = sh(["systemctl", "is-active", SERVICE])
    enabled = sh(["systemctl", "is-enabled", SERVICE])
    since = sh(["systemctl", "show", SERVICE, "-p", "ActiveEnterTimestamp",
                "--value"])
    logs = sh(["journalctl", "-u", SERVICE, "-n", "25", "--no-pager", "-o",
               "short-iso"])

    connected = None
    for line in reversed(logs.splitlines()):
        if "Device found" in line:
            connected = True
            break
        if "disconnected" in line:
            connected = False
            break

    return {
        "active": active,
        "enabled": enabled,
        "since": since,
        "connected": connected,
        "logs": logs.splitlines()[-25:],
    }


def run_privileged(args):
    """Run mouse-apply as root, preferring a graphical prompt when we have one."""
    graphical = bool(os.environ.get("DISPLAY") or os.environ.get("WAYLAND_DISPLAY"))
    attempts = []
    if graphical and shutil.which("pkexec"):
        attempts.append(["pkexec", APPLY_HELPER, *args])
    attempts.append(["sudo", "-n", APPLY_HELPER, *args])

    last = None
    for cmd in attempts:
        try:
            r = subprocess.run(cmd, capture_output=True, text=True, timeout=120)
        except FileNotFoundError:
            continue
        except subprocess.TimeoutExpired:
            return False, "timed out waiting for authentication"
        if r.returncode == 0:
            return True, (r.stdout or "").strip()
        last = (r.stderr or r.stdout or "").strip()
        # 126/127 from pkexec mean dismissed/not-authorised; try the next path.
        if cmd[0] == "pkexec" and r.returncode in (126, 127):
            continue
        return False, last
    return False, last or (
        "could not gain root. Run `sudo -v` in a terminal first, or install "
        "policykit-1 so the graphical prompt works."
    )


def apply_config(text):
    fd, path = tempfile.mkstemp(prefix="m720-", suffix=".cfg")
    try:
        with os.fdopen(fd, "w") as fh:
            fh.write(text)
        os.chmod(path, 0o644)   # pkexec drops to a clean env; keep it readable
        return run_privileged([path])
    finally:
        try:
            os.unlink(path)
        except OSError:
            pass


def load_profiles():
    try:
        data = json.loads(PROFILES_FILE.read_text())
        if isinstance(data, dict) and isinstance(data.get("profiles"), dict):
            return data
    except (OSError, ValueError):
        pass
    return {"active": "Default", "profiles": {}}


def save_profiles(data):
    CONFIG_HOME.mkdir(parents=True, exist_ok=True)
    tmp = PROFILES_FILE.with_suffix(".tmp")
    tmp.write_text(json.dumps(data, indent=2))
    tmp.replace(PROFILES_FILE)


# --------------------------------------------------------------------------
# HTTP
# --------------------------------------------------------------------------

class Handler(BaseHTTPRequestHandler):
    server_version = "m720-config"
    token = ""

    def log_message(self, fmt, *args):
        pass  # keep the terminal clean

    # -- helpers ----------------------------------------------------------
    def _send(self, code, body, ctype="application/json"):
        if not isinstance(body, bytes):
            body = body.encode()
        self.send_response(code)
        self.send_header("Content-Type", ctype)
        self.send_header("Content-Length", str(len(body)))
        self.send_header("Cache-Control", "no-store")
        self.send_header("X-Content-Type-Options", "nosniff")
        self.end_headers()
        self.wfile.write(body)

    def _json(self, code, obj):
        self._send(code, json.dumps(obj))

    def _authorised(self):
        if self.headers.get("X-Token") == self.token:
            return True
        return self.path.split("?token=")[-1].split("&")[0] == self.token

    def _body(self):
        length = int(self.headers.get("Content-Length") or 0)
        if length <= 0 or length > 512_000:
            return {}
        try:
            return json.loads(self.rfile.read(length) or b"{}")
        except ValueError:
            return {}

    # -- routes -----------------------------------------------------------
    def do_GET(self):
        route = self.path.split("?")[0]

        if route == "/":
            if not self._authorised():
                return self._send(403, "Bad or missing token. Re-run `mouse modify`.",
                                  "text/plain")
            try:
                html = UI_FILE.read_text()
            except OSError as exc:
                return self._send(500, f"cannot read ui.html: {exc}", "text/plain")
            html = html.replace("__TOKEN__", self.token)
            return self._send(200, html, "text/html; charset=utf-8")

        if not self._authorised():
            return self._json(403, {"error": "bad token"})

        if route == "/api/state":
            text, err = read_current_config()
            return self._json(200, {
                "buttons": BUTTONS,
                "current": parse_config(text),
                "raw": text or "",
                "readError": err,
                "profiles": load_profiles(),
                "service": service_status(),
                "scroll": imwheel_state(),
            })

        if route == "/api/status":
            return self._json(200, service_status())

        return self._json(404, {"error": "not found"})

    def do_POST(self):
        route = self.path.split("?")[0]
        if not self._authorised():
            return self._json(403, {"error": "bad token"})

        if route == "/api/preview":
            try:
                return self._json(200, {"config": generate_config(self._body())})
            except Exception as exc:
                return self._json(400, {"error": f"could not build config: {exc}"})

        if route == "/api/apply":
            body = self._body()
            try:
                text = generate_config(body)
            except Exception as exc:
                return self._json(400, {"error": f"could not build config: {exc}"})
            ok, message = apply_config(text)
            # Scroll speed is a separate, unprivileged mechanism (imwheel), so
            # apply it either way — a logid rollback does not invalidate it.
            sok, smsg = apply_scroll(body.get("settings"))
            return self._json(200 if ok else 500, {
                "ok": ok, "message": message, "config": text,
                "scrollOk": sok, "scrollMessage": smsg,
                "service": service_status(), "scroll": imwheel_state(),
            })

        if route == "/api/revert":
            ok, message = run_privileged(["--revert"])
            return self._json(200 if ok else 500, {
                "ok": ok, "message": message, "service": service_status(),
            })

        if route == "/api/profiles":
            body = self._body()
            if not isinstance(body.get("profiles"), dict):
                return self._json(400, {"error": "malformed profiles payload"})
            try:
                save_profiles({"active": body.get("active", "Default"),
                               "profiles": body["profiles"]})
            except OSError as exc:
                return self._json(500, {"error": str(exc)})
            return self._json(200, {"ok": True})

        if route == "/api/quit":
            threading.Timer(0.3, lambda: os._exit(0)).start()
            return self._json(200, {"ok": True})

        return self._json(404, {"error": "not found"})


def main():
    if not UI_FILE.exists():
        sys.exit(f"m720-config: {UI_FILE} is missing — reinstall m720-config")

    Handler.token = secrets.token_urlsafe(24)

    httpd = None
    for port in range(8770, 8800):
        try:
            httpd = ThreadingHTTPServer(("127.0.0.1", port), Handler)
            break
        except OSError:
            continue
    if httpd is None:
        sys.exit("m720-config: no free port in 8770-8799")

    url = f"http://127.0.0.1:{httpd.server_port}/?token={Handler.token}"
    print("M720 configuration UI")
    print(f"  {url}")
    print("Leave this running while you configure. Ctrl-C to stop.")

    if "--no-browser" not in sys.argv:
        threading.Timer(0.4, lambda: webbrowser.open(url)).start()

    try:
        httpd.serve_forever()
    except KeyboardInterrupt:
        print("\nstopped.")


if __name__ == "__main__":
    main()
